//
//  ListPlacesRouter.swift
//  GoodPlaces
//
//  Created by Lucas  N Santana on 27/11/20.
//  Copyright (c) 2020 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListPlacesRoutingLogic {
    func routeToDetail()
}

protocol ListPlacesDataPassing {
    var dataStore: ListPlacesDataStore? { get }
}

class ListPlacesRouter: NSObject, ListPlacesRoutingLogic, ListPlacesDataPassing {
    weak var viewController: ListPlacesViewController?
    var dataStore: ListPlacesDataStore?
    
    // MARK: Routing
    func routeToDetail() {
        let destinationVC = DetailPlaceViewController()
        var destinationDS = destinationVC.router!.dataStore!
        
        passDataToDetail(source: dataStore!, destination: &destinationDS)
        navigateToDetail(source: viewController!, destination: destinationVC)
        
    }
    
    // MARK: Navigation
    
    func navigateToDetail(source: ListPlacesViewController, destination: DetailPlaceViewController) {
      source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToDetail(source: ListPlacesDataStore, destination: inout DetailPlaceDataStore) {
      destination.place = source.placeSelected
    }
}
