//
//  ListPlacesModels.swift
//  GoodPlaces
//
//  Created by Lucas  N Santana on 27/11/20.
//  Copyright (c) 2020 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListPlaces {
  enum List {
    struct Response {
        var places: [Place]
    }
    struct ViewModel {
        var itens: [ListPlaceViewModel]
    }
    struct ListPlaceViewModel {
        var name: String
        var openNow: String
        var rating: String
        var distance: String
    }
  }
}
