//
//  DetailPlaceModels.swift
//  GoodPlaces
//
//  Created by Lucas  N Santana on 02/12/20.
//  Copyright (c) 2020 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailPlace {
    // MARK: Use cases
    enum Detail {
        struct Response {
            var place: Place?
        }
        struct ViewModel {
            var iconUrl: String?
            var name: String
            var address: String
            var distance: String
            var types: String
            var rating: String
            var phoneBtn: String
            var reviews: [String]
        }
    }
}
