//
//  DetailPlaceRouter.swift
//  GoodPlaces
//
//  Created by Lucas  N Santana on 02/12/20.
//  Copyright (c) 2020 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPlaceDataPassing {
    var dataStore: DetailPlaceDataStore? { get }
}

class DetailPlaceRouter: NSObject, DetailPlaceDataPassing {
    weak var viewController: DetailPlaceViewController?
    var dataStore: DetailPlaceDataStore?
}
