//
//  DetailPlaceWorker.swift
//  GoodPlaces
//
//  Created by Lucas  N Santana on 02/12/20.
//  Copyright (c) 2020 Lucas  N Santana. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailPlaceWorker {
    private var googleService: GoogleServicesProtocol!
    init(){
        googleService = GoogleServices()
    }
    func getDetailWith(place: Place, completion: @escaping(Result<Place,ServiceError>)->()) {
        guard let placeID = place.placeID else {
            completion(.failure(ServiceError("Impossible to get details from this placeID.")))
            return
        }
        googleService.details(PlaceDetailRequest(placeID: placeID)) { (response:PlaceDetailResponse?, error:ServiceError?) in
            guard let place = response?.result else {
                completion(.failure(error ?? ServiceError()))
                return
            }
            completion(.success(place))
        }
    }
}
